### ISSUE TITLE
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

### ISSUE THREAD

**Issue by fqdeng** [lc4t/clean-baidutieba#4]
[2017-05-11 19:21:54.751808] -->https://tieba.baidu.com
Traceback (most recent call last):
  File "clean_tieba.py", line 331, in <module>
    tieba.login()
  File "clean_tieba.py", line 233, in login
    _ = self.r.get(url)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 597, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 597, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 113, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

**Comment by lc4t** [comment]
Sorry I do not know how you cause this. And I try again it works successful.
May you input right cookie, or your network works well?

**Comment by zyxbcde** [comment]
成功复现了问题，原因是看不见的各式问题，把cookie直接贴到程序里就这样，把cookie先贴到记事本里取消自动换行就好了。
